FROM registry.redhat.io/rhel9/rhel-bootc:9.6

RUN useradd -m -d /var/home/kiosk kiosk 

RUN dnf install -y shadow-utils gnome-kiosk gdm gnome-kiosk-script-session  git firefox \
    && dnf clean all

RUN mkdir -p /var/home/kiosk/.local/bin/ /etc/accountsservice/user-templates /etc/gdm/

COPY files/gnome-kiosk-script /var/home/kiosk/.local/bin/
COPY files/user-templates-standard /etc/accountsservice/user-templates/standard
COPY files/gdm-custom.conf    /etc/gdm/custom.conf

RUN chmod +x /var/home/kiosk/.local/bin/gnome-kiosk-script && \
    chown -R kiosk:kiosk /var/home/kiosk

RUN systemctl set-default graphical.target

#////////////////////////////////////////
#DEMO V2 update (cockpit + kvm + firewall)
#////////////////////////////////////////
#RUN dnf install -y cockpit cockpit-podman cockpit-system cockpit-bridge cockpit-pcp cockpit-storaged cockpit-session-recording  \
#    && dnf clean all
#
#RUN systemctl enable cockpit.socket
#////////////////////////////////////////

