FROM registry.redhat.io/rhel9/rhel-bootc:9.6

RUN dnf install -y shadow-utils libvirt-daemon-config-network libvirt-daemon-kvm qemu-kvm qemu-img libvirt virt-install virt-viewer libguestfs-tools python3-libguestfs virt-top  \
    && dnf clean all

RUN for drv in qemu network nodedev nwfilter secret storage interface; do systemctl enable virt${drv}d{,-ro,-admin}.socket; done


#////////////////////////////////////////
#DEMO V2 update (cockpit )
#////////////////////////////////////////
#RUN dnf install -y  cockpit cockpit-machines cockpit-podman cockpit-system cockpit-bridge cockpit-pcp cockpit-storaged cockpit-session-recording \
#    && dnf clean all
#
#RUN systemctl enable cockpit.socket
#////////////////////////////////////////


