FROM registry.redhat.io/rhel9/rhel-bootc:9.6

ENV LANG=en_US.UTF-8

# Package dependencies
RUN dnf install -y curl dnf-plugins-core langpacks-en glibc-langpack-en 'dnf-command(config-manager)' https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm  && \
    dnf config-manager --set-enabled codeready-builder-for-rhel-9-$(arch)-rpms && \
    dnf clean all

# Development tools
RUN dnf install -y \
        cmake \
        gcc-c++ \
        git \
        make \
        patch \
        python3-colcon-common-extensions \
        python3-mypy \
        python3-pip \
        python3-pytest \
        python3-pytest-cov \
        python3-pytest-mock \
        python3-pytest-repeat \
        python3-pytest-rerunfailures \
        python3-pytest-runner \
        python3-rosdep \
        python3-setuptools \
        python3-vcstool \
        wget && \
    python3 -m pip install -U --user \
        flake8-blind-except==0.1.1 \
        flake8-class-newline \
        flake8-deprecated && \
    dnf clean all

# Download and install ROS release using RPMs
RUN ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') && \ 
    dnf install -y "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-release-${ROS_APT_SOURCE_VERSION}-1.noarch.rpm" && \
    dnf install -y ros-kilted-desktop && \
    dnf clean all

# Install from source
RUN mkdir -p ~/ros2_kilted/src && \
    cd ~/ros2_kilted && \
    vcs import --input https://raw.githubusercontent.com/ros2/ros2/kilted/ros2.repos src  && \
    rosdep update  && \
    rosdep install --from-paths src --ignore-src -y --skip-keys "fastcdr rti-connext-dds-7.3.0 urdfdom_headers"