# Builds a basic RHEL Bootc image for NVIDIA Tegra SOC with Nvidia CDI enabled

# The packages from NVIDIA's repo are only built for specific versions of RHEL, be sure to pin the exact tag
FROM registry.redhat.io/rhel9/rhel-bootc@sha256:031d9c863945013c82c7c087ac7eff5f4d608658374cbe06085c59762e1bdd65

# Install NVIDIA jetpack components
# Mask nvpower.service (causes kernel panic)
# Remove upstream host1x kernel module (conflicts with nvidia provided one)

# Container image with nvidia jetson RPMs
COPY --from=quay.io/luisarizmendi/rhel-nvidia-jetson-rpms:9.6 /artifacts/ /tmp/artifact/

RUN ls /tmp/artifact/

RUN dnf -y install /tmp/artifact/*.rpm && \
    dnf clean all && \
    systemctl mask nvfancontrol.service nvpmodel.service nvpower.service && \
    rm -r /tmp/artifact && \
    rm /usr/lib/modules/*/kernel/drivers/gpu/host1x/host1x.ko.xz

# Regenerate initrd (just in case)
RUN set -x; kver=$(cd /usr/lib/modules && echo *); dracut -vf /usr/lib/modules/$kver/initramfs.img $kver

# Install NVIDIA container toolkit
RUN curl -s -L https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo | \
    tee /etc/yum.repos.d/nvidia-container-toolkit.repo && \
    dnf -y install nvidia-container-toolkit && \
    dnf clean all

# Create and enable a systemd service to generate the NVIDIA CDI YAML file
RUN cat <<EOF > /etc/systemd/system/nvidia-cdi.service
[Unit]
Description=Generate the nvidia cdi yaml file
Requires=multi-user.target
Requires=systemd-modules-load.service
After=multi-user.target
After=systemd-modules-load.service

[Service]
Type=oneshot
ExecStartPre=bash -c "echo 1 > /dev/nvgpu/igpu0/power"
ExecStart=nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
RUN systemctl enable nvidia-cdi

# Modify bootc-generic-growpart service to remove virtualization condition
# so that the root partition is expanded to fill the entire disk
RUN sed -i '/ConditionVirtualization=vm/d' /usr/lib/systemd/system/bootc-generic-growpart.service

# Configure sudoers to allow wheel group members to run commands without password
RUN cat <<CFG > /etc/sudoers.d/wheel-nopasswd
%wheel ALL=(ALL) NOPASSWD: ALL
CFG

# Load the i2c-dev kernel module at boot
# for jetson_stats
RUN cat <<EOF > /etc/modules-load.d/i2c-dev.conf
i2c-dev
EOF

# Add kernel arguments for Jetson devices
# disable selinux, and set the correct console device
RUN cat <<EOF > /usr/lib/bootc/kargs.d/10-jetson.toml
kargs = ["enforcing=0", "console=ttyTCU0,115200"]
EOF
